defaults:
  - _self_
  - override hydra/job_logging: custom

task_name: npt_training
run_name: pilot_run
device: cuda

data:
  train_file: data/tiny_stories_train.tokens.uint16.npy 
  val_file: data/tiny_stories_val.tokens.uint16.npy
  batch_size: 128 
  seq_len: 256 
   
model:
  d_model: 512 
  d_ff: 1344 
  num_heads: 16
  vocab_size: 10000
  num_transformer_layers: 4
  rope_theta: 10000.0
  context_len: ${data.seq_len}

optim:
  lr: 3e-4 
  weight_decay: 0.1
  betas: [0.9, 0.999]
  eps: 1e-8
  # cosine warmup
  min_lr: 1e-5
  warmup_iters: 2000
  cosine_cyle_iters: 10000 

trainer:
  total_steps: 10000
  save_dir: checkpoints/${run_name}
  val_freq: 1000
  val_steps: 500 
  save_freq: 1000
  log_freq: 10
  resume_checkpoint_path: null
  resume: false